### PR TITLE
Mff badge style

### PR DESCRIPTION
**Pull request by ianlayton**
Changes to the badge design for MFF 2017

### CODE REVIEW

**Comment by kitsuta** [comment]
This was already implemented elsewhere using templating overrides, as described in https://github.com/MidwestFurryFandom/badge_printing/pull/1. The changes should be visible once staging gets re-deployed.

**Comment by kitsuta** [comment]
Addendum: It looks like the template is different from #1, so I'll make sure to echo those changes!

**Comment by ianlayton** [comment]
Yeah...I'm sorry for the confusion on this. I think me and @jmdawson put in about the same code. Most of the stuff is the same, but there is some cleanup done. (like removing that comment and making sure the auto refresh was turned back on)

**Comment by kitsuta** [comment]
Np! I saw there were updates to the template too, so it's good to make sure those get in. :) Updates are in https://github.com/MidwestFurryFandom/mff-rams-plugin/commit/7e8846c655e4e1a1a05a5512a2867e01fbe68f83!

**Pull request closed without merging**
